### ISSUE TITLE
Issue when trying to create a resource URL route

### ISSUE THREAD

**Issue by etiennemarais** [bstrahija/l4-site-tutorial#8]
Hi,

I am working through your tutorial and it seems like there is an issue with generating the proper resource URL for show etc.

Specifically In File: /app/views/admin/pages/index.blade.php

{{ URL::route('admin.pages.show', $page->id) }}

I get the error: "array_shift() expects parameter 1 to be array, integer given" when trying to generate that URL. Do you know why that is?

Thank you

**Comment by bstrahija** [comment]
Can you share your routes.php file? Maybe on: http://paste.laravel.com/
Also any routes you have in your themes dir.

**Comment by etiennemarais** [comment]
http://paste.laravel.com/OvI is the view file it breaks in.

http://paste.laravel.com/OvJ is the routes.php file

**Comment by bstrahija** [comment]
Can you also try running "php artisan routes" and copying the output somewhere?

**Comment by etiennemarais** [comment]
http://paste.laravel.com/OvM [edit] The updated version of all routes

**Comment by bstrahija** [comment]
Everything seems ok, I don't see any issues, hm. Can you var_dump the $page object in your view?

**Comment by etiennemarais** [comment]
http://paste.laravel.com/Ow4 

Thats the output from a page var_dump

**Comment by bstrahija** [comment]
Sorry, but I can't see what's wrong here. Does the error persist on a fresh install?

**Comment by jadbirch** [comment]
I would try passing in $page->ID as an array like so:

```
{{ URL::route('admin.pages.show', array($page->id)) }}
```

I digged around in the source code and I can't see anywhere where array_shift is explicitly called - it doesn't seem to be called by the route function at least - but clearly somewhere along the line it is being called and is expecting the params to be in an array. Give it a try.

Edit: the route function calls the toRoute function which in turn calls preg_replace_sub to build the path. Preg_replace_sub uses array_shift on its second parameter (in this case $page->id) and thus returns an error here because array_shift can only be called on an array. I expect that the solution above would resolve the issue.

**Comment by etiennemarais** [comment]
Hi, Thank you that seems to have solved the issue. Thanks for digging so deep
